// <auto-generated />
using System;
using KooperatifYonetim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooperatifYonetim.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.Ahir", b =>
                {
                    b.Property<int>("AhirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AhirId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("HayvanSayisi")
                        .HasColumnType("int");

                    b.Property<string>("UreticiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AhirId");

                    b.HasIndex("UreticiId");

                    b.ToTable("Ahirlar");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.Arazi", b =>
                {
                    b.Property<int>("AraziId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AraziId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<double>("Boylam")
                        .HasColumnType("float");

                    b.Property<double>("Enlem")
                        .HasColumnType("float");

                    b.Property<string>("UreticiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("YuzOlcumu")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("AraziId");

                    b.HasIndex("UreticiId");

                    b.ToTable("Araziler");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.BesiStok", b =>
                {
                    b.Property<int>("StokId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StokId"));

                    b.Property<int>("AhirId")
                        .HasColumnType("int");

                    b.Property<string>("BesiTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EsikMiktar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MevcutMiktar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.HasKey("StokId");

                    b.HasIndex("AhirId");

                    b.ToTable("BesiStoklar");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.Ekin", b =>
                {
                    b.Property<int>("EkinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EkinId"));

                    b.Property<int>("AraziId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime>("EkimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EkinTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HasatTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("EkinId");

                    b.HasIndex("AraziId");

                    b.ToTable("Ekinler");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.GunlukBesiGirisi", b =>
                {
                    b.Property<int>("GirisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GirisId"));

                    b.Property<int>("AhirId")
                        .HasColumnType("int");

                    b.Property<string>("BesiTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("YedirildenMiktar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("GirisId");

                    b.HasIndex("AhirId");

                    b.ToTable("GunlukBesiGirisleri");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.HayvanHastalikBildirimi", b =>
                {
                    b.Property<int>("BildirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AhirId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BildirimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("UreticiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VeterinerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BildirimId");

                    b.HasIndex("AhirId");

                    b.HasIndex("UreticiId");

                    b.HasIndex("VeterinerId");

                    b.ToTable("HayvanHastalikBildirimler");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.SutUretimi", b =>
                {
                    b.Property<int>("SutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SutId"));

                    b.Property<int>("AhirId")
                        .HasColumnType("int");

                    b.Property<string>("MandiraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("SutId");

                    b.HasIndex("AhirId");

                    b.HasIndex("MandiraId");

                    b.ToTable("SutUretimleri");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.TarimHastalikBildirimi", b =>
                {
                    b.Property<int>("BildirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BildirimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("EkinId")
                        .HasColumnType("int");

                    b.Property<string>("MuhendisId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UreticiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BildirimId");

                    b.HasIndex("EkinId");

                    b.HasIndex("MuhendisId");

                    b.HasIndex("UreticiId");

                    b.ToTable("TarimHastalikBildirimler");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.TarimIslem", b =>
                {
                    b.Property<int>("IslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslemId"));

                    b.Property<int>("EkinId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GerceklesenTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("IslemTuru")
                        .HasColumnType("int");

                    b.Property<decimal?>("Miktar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlanlananTarih")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("bit");

                    b.HasKey("IslemId");

                    b.HasIndex("EkinId");

                    b.ToTable("TarimIslemler");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.UrunTemin", b =>
                {
                    b.Property<int>("UrunTeminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunTeminId"));

                    b.Property<decimal?>("AlinanMiktar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("AraziId")
                        .HasColumnType("int");

                    b.Property<string>("Donem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PlanlananMiktar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ToptanciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UrunTeminId");

                    b.HasIndex("AraziId");

                    b.HasIndex("ToptanciId");

                    b.ToTable("UrunTeminler");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.VeterinerBakim", b =>
                {
                    b.Property<int>("BakimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BakimId"));

                    b.Property<int>("AhirId")
                        .HasColumnType("int");

                    b.Property<int>("BakimTuru")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GerceklesenTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlanlananTarih")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("bit");

                    b.Property<string>("VeterinerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BakimId");

                    b.HasIndex("AhirId");

                    b.HasIndex("VeterinerId");

                    b.ToTable("VeterinerBakimlar");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.Ahir", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", "Uretici")
                        .WithMany("Ahirlar")
                        .HasForeignKey("UreticiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uretici");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.Arazi", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", "Uretici")
                        .WithMany("Araziler")
                        .HasForeignKey("UreticiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uretici");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.BesiStok", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.Ahir", "Ahir")
                        .WithMany("BesiStoklar")
                        .HasForeignKey("AhirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ahir");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.Ekin", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.Arazi", "Arazi")
                        .WithMany("Ekinler")
                        .HasForeignKey("AraziId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arazi");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.GunlukBesiGirisi", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.Ahir", "Ahir")
                        .WithMany("GunlukBesiGirisler")
                        .HasForeignKey("AhirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ahir");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.HayvanHastalikBildirimi", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.Ahir", "Ahir")
                        .WithMany("HayvanHastalikBildirimler")
                        .HasForeignKey("AhirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", "Uretici")
                        .WithMany()
                        .HasForeignKey("UreticiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", "Veteriner")
                        .WithMany()
                        .HasForeignKey("VeterinerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ahir");

                    b.Navigation("Uretici");

                    b.Navigation("Veteriner");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.SutUretimi", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.Ahir", "Ahir")
                        .WithMany("SutUretimler")
                        .HasForeignKey("AhirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", "Mandira")
                        .WithMany()
                        .HasForeignKey("MandiraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ahir");

                    b.Navigation("Mandira");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.TarimHastalikBildirimi", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.Ekin", "Ekin")
                        .WithMany("HastalıkBildirimler")
                        .HasForeignKey("EkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", "Muhendis")
                        .WithMany()
                        .HasForeignKey("MuhendisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", "Uretici")
                        .WithMany()
                        .HasForeignKey("UreticiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ekin");

                    b.Navigation("Muhendis");

                    b.Navigation("Uretici");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.TarimIslem", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.Ekin", "Ekin")
                        .WithMany("TarimIslemler")
                        .HasForeignKey("EkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekin");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.UrunTemin", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.Arazi", "Arazi")
                        .WithMany("UrunTeminler")
                        .HasForeignKey("AraziId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", "Toptanci")
                        .WithMany()
                        .HasForeignKey("ToptanciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arazi");

                    b.Navigation("Toptanci");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.VeterinerBakim", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.Ahir", "Ahir")
                        .WithMany("VeterinerBakimlar")
                        .HasForeignKey("AhirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", "Veteriner")
                        .WithMany()
                        .HasForeignKey("VeterinerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ahir");

                    b.Navigation("Veteriner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KooperatifYonetim.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.Ahir", b =>
                {
                    b.Navigation("BesiStoklar");

                    b.Navigation("GunlukBesiGirisler");

                    b.Navigation("HayvanHastalikBildirimler");

                    b.Navigation("SutUretimler");

                    b.Navigation("VeterinerBakimlar");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.AppUser", b =>
                {
                    b.Navigation("Ahirlar");

                    b.Navigation("Araziler");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.Arazi", b =>
                {
                    b.Navigation("Ekinler");

                    b.Navigation("UrunTeminler");
                });

            modelBuilder.Entity("KooperatifYonetim.Core.Entities.Ekin", b =>
                {
                    b.Navigation("HastalıkBildirimler");

                    b.Navigation("TarimIslemler");
                });
#pragma warning restore 612, 618
        }
    }
}
